version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-database

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      - POSTGRES_PASSWORD=ExploreWithMe
      - POSTGRES_USER=explorewithme
      - POSTGRES_DB=stats-database

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore-with-me-database

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    environment:
      - POSTGRES_PASSWORD=ExploreWithMe
      - POSTGRES_USER=explorewithme
      - POSTGRES_DB=explore-with-me-database
